sudo: required

env:
  - VERSION=latest URL=https://www-eu.apache.org/dist/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz
  - VERSION=3.0.0 URL=https://www-eu.apache.org/dist/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz

services:
   - docker

script:
   - make build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy
     on:
        all_branches: true
